project 'AliceOnboardingSampleApp.xcodeproj'
platform :ios, '12.0'

target 'AliceOnboardingSampleApp' do
    project 'AliceOnboardingSampleApp.xcodeproj'
    pod 'AliceOnboarding'
    pod 'TransitionButton'
end