project 'AppOnboardingSample.xcodeproj'
platform :ios, '12.0'
use_frameworks!

target 'AppOnboardingSample' do
    project 'AppOnboardingSample.xcodeproj'
    pod 'AliceOnboarding'
    pod 'TransitionButton'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == "Debug" && defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
                config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
            end 
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end 
