name: ci

on:
  release:
    types: [published]
  push:
    paths:
      - '.github/workflows/ci.yml'


jobs:
  ci:
    runs-on: macOS-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Pod install
        working-directory: AliceOnboardingSampleApp/
        run: |
           pod install --repo-update
           
      - name: Tests [UI Test]
        working-directory: AliceOnboardingSampleApp/
        run: |
           xcodebuild -workspace AliceOnboardingSampleApp.xcworkspace  -scheme AliceOnboardingSampleApp  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.2'  test
